// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import 'client/hostel.dart';

// These functions are ignored because they are not marked as `pub`: `decode_base64_image`, `flatten`, `max_soft`, `pre_img`, `saturation`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BITMAPS`, `WEIGHTS_DATA`, `Weights`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

/// Solves the captcha from a base64 encoded image string.
Future<VtopResultString> solveCaptcha({required String captchaData}) => RustLib
    .instance
    .api
    .crateApiVtopCaptchaSolverSolveCaptcha(captchaData: captchaData);
