// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../frb_generated.dart';
import 'vtop_client.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions have error during generation (see debug logs or enable `stop_on_error: true` for more details): `timeout`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VtopClientBuilder>>
abstract class VtopClientBuilder implements RustOpaqueInterface {
  Future<VtopClient> build({
    required String username,
    required String password,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VtopClientBuilder> newInstance() =>
      RustLib.instance.api.crateApiVtopVtopConfigVtopClientBuilderNew();
}

class VtopConfig {
  final String baseUrl;
  final BigInt timeoutSeconds;
  final String userAgent;

  const VtopConfig({
    required this.baseUrl,
    required this.timeoutSeconds,
    required this.userAgent,
  });

  static Future<VtopConfig> default_() =>
      RustLib.instance.api.crateApiVtopVtopConfigVtopConfigDefault();

  @override
  int get hashCode =>
      baseUrl.hashCode ^ timeoutSeconds.hashCode ^ userAgent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VtopConfig &&
          runtimeType == other.runtimeType &&
          baseUrl == other.baseUrl &&
          timeoutSeconds == other.timeoutSeconds &&
          userAgent == other.userAgent;
}
