// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'attendance.freezed.dart';
part 'attendance.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class AttendanceDetailRecord with _$AttendanceDetailRecord {
  const factory AttendanceDetailRecord({
    required String serial,
    required String date,
    required String slot,
    required String dayTime,
    required String status,
    required String remark,
  }) = _AttendanceDetailRecord;

  factory AttendanceDetailRecord.fromJson(Map<String, dynamic> json) =>
      _$AttendanceDetailRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class AttendanceRecord with _$AttendanceRecord {
  const factory AttendanceRecord({
    required String classNumber,
    required String courseCode,
    required String courseName,
    required String courseType,
    required String courseTypeCode,
    required String courseSlot,
    required String faculty,
    required String attendedClasses,
    required String totalClasses,
    required String attendancePercentage,
    required String attendanceBetweenPercentage,
    required String debarStatus,
    required String courseId,
  }) = _AttendanceRecord;

  factory AttendanceRecord.fromJson(Map<String, dynamic> json) =>
      _$AttendanceRecordFromJson(json);
}
