// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'biometric.freezed.dart';
part 'biometric.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class BiometricRecord with _$BiometricRecord {
  const factory BiometricRecord({
    required String serial,
    required String date,
    required String day,
    required String inTime,
    required String outTime,
    required String duration,
    required String location,
  }) = _BiometricRecord;

  factory BiometricRecord.fromJson(Map<String, dynamic> json) =>
      _$BiometricRecordFromJson(json);
}
