// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FacultyOption`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Represents a class entry in the course slots table
class CourseClassEntry {
  /// Serial number
  final int slNo;

  /// Class group (e.g., "General (Semester)")
  final String classGroup;

  /// Course code
  final String courseCode;

  /// Course title
  final String courseTitle;

  /// Course type (e.g., "Embedded Theory")
  final String courseType;

  /// Class ID
  final String classId;

  /// Slot (e.g., "E1/TE1")
  final String slot;

  /// Faculty info (e.g., "70735 - Shaik Subhani - SCOPE")
  final String faculty;

  /// Semester ID
  final String semesterId;

  /// Faculty ERP ID for view action
  final String erpId;

  const CourseClassEntry({
    required this.slNo,
    required this.classGroup,
    required this.courseCode,
    required this.courseTitle,
    required this.courseType,
    required this.classId,
    required this.slot,
    required this.faculty,
    required this.semesterId,
    required this.erpId,
  });

  @override
  int get hashCode =>
      slNo.hashCode ^
      classGroup.hashCode ^
      courseCode.hashCode ^
      courseTitle.hashCode ^
      courseType.hashCode ^
      classId.hashCode ^
      slot.hashCode ^
      faculty.hashCode ^
      semesterId.hashCode ^
      erpId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseClassEntry &&
          runtimeType == other.runtimeType &&
          slNo == other.slNo &&
          classGroup == other.classGroup &&
          courseCode == other.courseCode &&
          courseTitle == other.courseTitle &&
          courseType == other.courseType &&
          classId == other.classId &&
          slot == other.slot &&
          faculty == other.faculty &&
          semesterId == other.semesterId &&
          erpId == other.erpId;
}

/// Represents course information in the detail view
class CourseInfo {
  /// Class group
  final String classGroup;

  /// Course code
  final String courseCode;

  /// Course title
  final String courseTitle;

  /// Course type
  final String courseType;

  /// Class ID
  final String classId;

  /// Slot
  final String slot;

  /// Faculty name
  final String faculty;

  /// Course ID (e.g., "AM_CSE2009_00110")
  final String courseId;

  const CourseInfo({
    required this.classGroup,
    required this.courseCode,
    required this.courseTitle,
    required this.courseType,
    required this.classId,
    required this.slot,
    required this.faculty,
    required this.courseId,
  });

  @override
  int get hashCode =>
      classGroup.hashCode ^
      courseCode.hashCode ^
      courseTitle.hashCode ^
      courseType.hashCode ^
      classId.hashCode ^
      slot.hashCode ^
      faculty.hashCode ^
      courseId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseInfo &&
          runtimeType == other.runtimeType &&
          classGroup == other.classGroup &&
          courseCode == other.courseCode &&
          courseTitle == other.courseTitle &&
          courseType == other.courseType &&
          classId == other.classId &&
          slot == other.slot &&
          faculty == other.faculty &&
          courseId == other.courseId;
}

/// Represents a course option available in the course page dropdown
class CourseOption {
  /// The unique identifier for the course (e.g., "AP2025264000394")
  final String value;

  /// The display name (e.g., "CSE2009 - Soft Computing - ETH")
  final String label;

  /// The course code extracted from label (e.g., "CSE2009")
  final String courseCode;

  /// The course title (e.g., "Soft Computing")
  final String courseTitle;

  /// The course type (e.g., "ETH", "EPJ", "ELA", "TH")
  final String courseType;

  const CourseOption({
    required this.value,
    required this.label,
    required this.courseCode,
    required this.courseTitle,
    required this.courseType,
  });

  @override
  int get hashCode =>
      value.hashCode ^
      label.hashCode ^
      courseCode.hashCode ^
      courseTitle.hashCode ^
      courseType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CourseOption &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          label == other.label &&
          courseCode == other.courseCode &&
          courseTitle == other.courseTitle &&
          courseType == other.courseType;
}

/// Represents the detailed course page with all materials
class CoursePageDetail {
  /// Course information
  final CourseInfo courseInfo;

  /// Semester ID
  final String semesterId;

  /// Download all materials path
  final String? downloadAllPath;

  /// Download general materials path
  final String? downloadGeneralMaterialsPath;

  /// Syllabus download path
  final String? syllabusDownloadPath;

  /// Course plan excel download path
  final String? coursePlanDownloadPath;

  /// All lectures with their materials
  final List<LectureEntry> lectures;

  const CoursePageDetail({
    required this.courseInfo,
    required this.semesterId,
    this.downloadAllPath,
    this.downloadGeneralMaterialsPath,
    this.syllabusDownloadPath,
    this.coursePlanDownloadPath,
    required this.lectures,
  });

  @override
  int get hashCode =>
      courseInfo.hashCode ^
      semesterId.hashCode ^
      downloadAllPath.hashCode ^
      downloadGeneralMaterialsPath.hashCode ^
      syllabusDownloadPath.hashCode ^
      coursePlanDownloadPath.hashCode ^
      lectures.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoursePageDetail &&
          runtimeType == other.runtimeType &&
          courseInfo == other.courseInfo &&
          semesterId == other.semesterId &&
          downloadAllPath == other.downloadAllPath &&
          downloadGeneralMaterialsPath == other.downloadGeneralMaterialsPath &&
          syllabusDownloadPath == other.syllabusDownloadPath &&
          coursePlanDownloadPath == other.coursePlanDownloadPath &&
          lectures == other.lectures;
}

/// Response for getting courses for a semester
class CoursesResponse {
  /// List of available courses
  final List<CourseOption> courses;

  const CoursesResponse({required this.courses});

  @override
  int get hashCode => courses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoursesResponse &&
          runtimeType == other.runtimeType &&
          courses == other.courses;
}

/// Represents a lecture entry in the course detail page
class LectureEntry {
  /// Serial number
  final int slNo;

  /// Lecture date (e.g., "10-12-2025")
  final String date;

  /// Formatted date (e.g., "10-Dec-2025")
  final String formattedDate;

  /// Day of week (e.g., "WED")
  final String day;

  /// Lecture topic
  final String topic;

  /// Reference materials attached to this lecture
  final List<ReferenceMaterial> referenceMaterials;

  const LectureEntry({
    required this.slNo,
    required this.date,
    required this.formattedDate,
    required this.day,
    required this.topic,
    required this.referenceMaterials,
  });

  @override
  int get hashCode =>
      slNo.hashCode ^
      date.hashCode ^
      formattedDate.hashCode ^
      day.hashCode ^
      topic.hashCode ^
      referenceMaterials.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LectureEntry &&
          runtimeType == other.runtimeType &&
          slNo == other.slNo &&
          date == other.date &&
          formattedDate == other.formattedDate &&
          day == other.day &&
          topic == other.topic &&
          referenceMaterials == other.referenceMaterials;
}

/// Represents a reference material attached to a lecture
class ReferenceMaterial {
  /// Material label (e.g., "Reference Material I")
  final String label;

  /// Download path (e.g., "downloadPdf/AP2025264/AP2025264000442/19/10-12-2025")
  final String downloadPath;

  const ReferenceMaterial({required this.label, required this.downloadPath});

  @override
  int get hashCode => label.hashCode ^ downloadPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReferenceMaterial &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          downloadPath == other.downloadPath;
}

/// Represents a slot option for a course
class SlotOption {
  /// The unique identifier for the slot (e.g., "3688")
  final String value;

  /// The slot display name (e.g., "E1+TE1")
  final String label;

  const SlotOption({required this.value, required this.label});

  @override
  int get hashCode => value.hashCode ^ label.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotOption &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          label == other.label;
}

/// Response for getting slots for a course
class SlotsResponse {
  /// List of available slots
  final List<SlotOption> slots;

  /// List of class entries
  final List<CourseClassEntry> classEntries;

  const SlotsResponse({required this.slots, required this.classEntries});

  @override
  int get hashCode => slots.hashCode ^ classEntries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SlotsResponse &&
          runtimeType == other.runtimeType &&
          slots == other.slots &&
          classEntries == other.classEntries;
}
