// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'digital_assignment.freezed.dart';
part 'digital_assignment.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class AssignmentRecordEach with _$AssignmentRecordEach {
  const factory AssignmentRecordEach({
    required String serialNumber,
    required String assignmentTitle,
    required String maxAssignmentMark,
    required String assignmentWeightageMark,
    required String dueDate,
    required bool canQpDownload,
    required String qpDownloadUrl,
    required String submissionStatus,
    required bool canUpdate,
    required String mcode,
    required bool canDaDownload,
    required String daDownloadUrl,
  }) = _AssignmentRecordEach;

  factory AssignmentRecordEach.fromJson(Map<String, dynamic> json) =>
      _$AssignmentRecordEachFromJson(json);
}

@freezed
@meta.immutable
sealed class DigitalAssignments with _$DigitalAssignments {
  const factory DigitalAssignments({
    required String serialNumber,
    required String classId,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String faculty,
    required List<AssignmentRecordEach> details,
  }) = _DigitalAssignments;

  factory DigitalAssignments.fromJson(Map<String, dynamic> json) =>
      _$DigitalAssignmentsFromJson(json);
}
