// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'exam_schedule.freezed.dart';
part 'exam_schedule.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class ExamScheduleRecord with _$ExamScheduleRecord {
  const factory ExamScheduleRecord({
    required String serialNumber,
    required String slot,
    required String courseName,
    required String courseCode,
    required String courseType,
    required String courseId,
    required String examDate,
    required String examSession,
    required String reportingTime,
    required String examTime,
    required String venue,
    required String seatLocation,
    required String seatNumber,
  }) = _ExamScheduleRecord;

  factory ExamScheduleRecord.fromJson(Map<String, dynamic> json) =>
      _$ExamScheduleRecordFromJson(json);
}

@freezed
@meta.immutable
sealed class PerExamScheduleRecord with _$PerExamScheduleRecord {
  const factory PerExamScheduleRecord({
    required List<ExamScheduleRecord> subjects,
    required String examType,
  }) = _PerExamScheduleRecord;

  factory PerExamScheduleRecord.fromJson(Map<String, dynamic> json) =>
      _$PerExamScheduleRecordFromJson(json);
}
