// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'faculty.freezed.dart';
part 'faculty.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class FacultyDetails with _$FacultyDetails {
  const factory FacultyDetails({
    required String name,
    required String designation,
    required String department,
    required String schoolCentre,
    required String email,
    required String cabinNumber,
    required List<OfficeHour> officeHours,
  }) = _FacultyDetails;

  factory FacultyDetails.fromJson(Map<String, dynamic> json) =>
      _$FacultyDetailsFromJson(json);
}

@freezed
@meta.immutable
sealed class GetFaculty with _$GetFaculty {
  const factory GetFaculty({
    required String facultyName,
    required String designation,
    required String schoolOrCentre,
    required String empId,
  }) = _GetFaculty;
}

@freezed
@meta.immutable
sealed class OfficeHour with _$OfficeHour {
  const factory OfficeHour({required String day, required String timings}) =
      _OfficeHour;

  factory OfficeHour.fromJson(Map<String, dynamic> json) =>
      _$OfficeHourFromJson(json);
}
