// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'general_outing.freezed.dart';
part 'general_outing.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class GeneralOutingRecord with _$GeneralOutingRecord {
  const factory GeneralOutingRecord({
    required String serial,
    required String registrationNumber,
    required String placeOfVisit,
    required String purposeOfVisit,
    required String fromDate,
    required String fromTime,
    required String toDate,
    required String toTime,
    required String status,
    required bool canDownload,
    required String leaveId,
  }) = _GeneralOutingRecord;

  factory GeneralOutingRecord.fromJson(Map<String, dynamic> json) =>
      _$GeneralOutingRecordFromJson(json);
}
