// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'grade_course_history.freezed.dart';
part 'grade_course_history.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class GradeCourseHistory with _$GradeCourseHistory {
  const factory GradeCourseHistory({
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String credits,
    required String grade,
    required String examMonth,
    required String courseDistribution,
  }) = _GradeCourseHistory;

  factory GradeCourseHistory.fromJson(Map<String, dynamic> json) =>
      _$GradeCourseHistoryFromJson(json);
}
