// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'marks.freezed.dart';
part 'marks.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class Marks with _$Marks {
  const factory Marks({
    required String serialNumber,
    required String courseCode,
    required String courseTitle,
    required String courseType,
    required String faculty,
    required String slot,
    required List<MarksRecordEach> details,
  }) = _Marks;

  factory Marks.fromJson(Map<String, dynamic> json) => _$MarksFromJson(json);
}

@freezed
@meta.immutable
sealed class MarksRecordEach with _$MarksRecordEach {
  const factory MarksRecordEach({
    required String serialNumber,
    required String markTitle,
    required String maxMark,
    required String weightage,
    required String status,
    required String scoredMark,
    required String weightageMark,
    required String remark,
  }) = _MarksRecordEach;

  factory MarksRecordEach.fromJson(Map<String, dynamic> json) =>
      _$MarksRecordEachFromJson(json);
}
