// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'mentor_details.freezed.dart';
part 'mentor_details.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class MentorDetails with _$MentorDetails {
  const factory MentorDetails({
    required String facultyId,
    required String facultyName,
    required String facultyDesignation,
    required String school,
    required String cabin,
    required String facultyDepartment,
    required String facultyEmail,
    required String facultyIntercom,
    required String facultyMobileNumber,
  }) = _MentorDetails;

  factory MentorDetails.fromJson(Map<String, dynamic> json) =>
      _$MentorDetailsFromJson(json);
}
