// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;

import '../../../frb_generated.dart';

part 'outing_info.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Student information pre-filled in outing forms
@freezed
sealed class OutingInfo with _$OutingInfo {
  const factory OutingInfo({
    required String registrationNumber,
    required String name,
    required String applicationNo,
    required String gender,
    required String hostelBlock,
    required String roomNumber,
    required String parentContactNumber,
  }) = _OutingInfo;
}
