// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'paid_payment_receipt.freezed.dart';
part 'paid_payment_receipt.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class PaidPaymentReceipt with _$PaidPaymentReceipt {
  const factory PaidPaymentReceipt({
    required String receiptNumber,
    required String date,
    required String amount,
    required String campusCode,
    required String paymentStatus,
    required String receiptNo,
  }) = _PaidPaymentReceipt;

  factory PaidPaymentReceipt.fromJson(Map<String, dynamic> json) =>
      _$PaidPaymentReceiptFromJson(json);
}
