// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'semester.freezed.dart';
part 'semester.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class SemesterData with _$SemesterData {
  const factory SemesterData({
    required List<SemesterInfo> semesters,
    required BigInt updateTime,
  }) = _SemesterData;

  factory SemesterData.fromJson(Map<String, dynamic> json) =>
      _$SemesterDataFromJson(json);
}

@freezed
@meta.immutable
sealed class SemesterInfo with _$SemesterInfo {
  const factory SemesterInfo({required String id, required String name}) =
      _SemesterInfo;

  factory SemesterInfo.fromJson(Map<String, dynamic> json) =>
      _$SemesterInfoFromJson(json);
}
