// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import 'grade_course_history.dart';
import 'grade_history.dart';
import 'mentor_details.dart';

part 'student_profile.freezed.dart';
part 'student_profile.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

@freezed
@meta.immutable
sealed class StudentProfile with _$StudentProfile {
  const factory StudentProfile({
    required String applicationNumber,
    required String studentName,
    required String dob,
    required String gender,
    required String bloodGroup,
    required String email,
    required String base64Pfp,
    required GradeHistory gradeHistory,
    required MentorDetails mentorDetails,
  }) = _StudentProfile;

  factory StudentProfile.fromJson(Map<String, dynamic> json) =>
      _$StudentProfileFromJson(json);
}
