// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'timetable.freezed.dart';
part 'timetable.g.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class Timetable with _$Timetable {
  const factory Timetable({
    required List<TimetableClass> monday,
    required List<TimetableClass> tuesday,
    required List<TimetableClass> wednesday,
    required List<TimetableClass> thursday,
    required List<TimetableClass> friday,
    required List<TimetableClass> saturday,
    required List<TimetableClass> sunday,
  }) = _Timetable;

  factory Timetable.fromJson(Map<String, dynamic> json) =>
      _$TimetableFromJson(json);
}

@freezed
@meta.immutable
sealed class TimetableClass with _$TimetableClass {
  const factory TimetableClass({
    required String startTime,
    required String endTime,
    required String courseName,
    required String slot,
    required String venue,
    required String faculty,
    required String courseCode,
    required String courseType,
  }) = _TimetableClass;

  factory TimetableClass.fromJson(Map<String, dynamic> json) =>
      _$TimetableClassFromJson(json);
}
