// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';

part 'weekend_outing.freezed.dart';
part 'weekend_outing.g.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `WeekendOutingFormData`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

@freezed
@meta.immutable
sealed class WeekendOutingRecord with _$WeekendOutingRecord {
  const factory WeekendOutingRecord({
    required String serial,
    required String registrationNumber,
    required String hostelBlock,
    required String roomNumber,
    required String placeOfVisit,
    required String purposeOfVisit,
    required String time,
    required String contactNumber,
    required String parentContactNumber,
    required String date,
    required String bookingId,
    required String status,
    required bool canDownload,
  }) = _WeekendOutingRecord;

  factory WeekendOutingRecord.fromJson(Map<String, dynamic> json) =>
      _$WeekendOutingRecordFromJson(json);
}
