// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../../frb_generated.dart';
import '../../types/faculty.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `extract_emp_id_from_row`

/// Parse the first matching faculty from a search-by-name/id response.
/// Used by the existing single-search flow.
Future<GetFaculty> parseFacultySearch({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserFacultyParsesearchParseFacultySearch(html: html);

/// Parse every row from the faculty-list response (e.g. empId=*).
/// Returns one `GetFaculty` per data row, skipping the header row.
Future<List<GetFaculty>> parseAllFacultySearch({required String html}) =>
    RustLib.instance.api
        .crateApiVtopParserFacultyParsesearchParseAllFacultySearch(html: html);
