// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/exam_schedule.dart';

Future<List<PerExamScheduleRecord>> parseSchedule({required String html}) =>
    RustLib.instance.api.crateApiVtopParserExamScheduleParserParseSchedule(
      html: html,
    );
