// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/grade_course_history.dart';
import '../types/grade_history.dart';

/// Parses an HTML string containing a student's grade history and extracts summary and course details.
///
/// Returns a `GradeHistory` struct containing credits registered, credits earned, CGPA, and a vector of course details.
///
/// # Examples
///
/// ```
/// let html = std::fs::read_to_string("tests/data/grade_history.html").unwrap();
/// let grade_history = parse_grade_history(html);
/// assert!(!grade_history.cgpa.is_empty());
/// assert!(!grade_history.courses.is_empty());
/// ```
Future<GradeHistory> parseGradeHistory({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserGradeHistoryParserParseGradeHistory(html: html);
