// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';
import '../types/outing_info.dart';
import '../vtop_errors.dart';

Future<OutingInfo> parseOutingForm({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserOutingFormParserParseOutingForm(html: html);
