// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../../../frb_generated.dart';

/// Parses the HTML response from VTOP outing submission/deletion endpoints.
///
/// VTOP returns two types of responses:
/// 1. Weekend outing: Simple span with message like "Weekend Outing Applied Successfully"
/// 2. General outing: SweetAlert modal with h2 tag like "Leave Applied Successfully"
Future<String> parseOutingResponse({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserOutingResponseParserParseOutingResponse(html: html);
