// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:meta/meta.dart' as meta;

import '../../../frb_generated.dart';
import '../types/grade_course_history.dart';
import '../types/grade_history.dart';
import '../types/mentor_details.dart';
import '../types/student_profile.dart';

/// Parses a student profile HTML page and returns a `StudentProfile` struct with extracted profile, mentor, and grade history details.
///
/// Extracts key student information, mentor (proctor) details, and the base64-encoded profile picture from the provided HTML.
/// Fields not present in the HTML are set to empty strings or `"N/A"` as appropriate.
///
/// # Examples
///
/// ```
/// let html = std::fs::read_to_string("student_profile.html").unwrap();
/// let profile = parse_student_profile(html);
/// assert!(!profile.student_name.is_empty());
/// ```
Future<StudentProfile> parseStudentProfile({required String html}) => RustLib
    .instance
    .api
    .crateApiVtopParserProfileParserParseStudentProfile(html: html);
